### ISSUE TITLE
libpysal.graph roadmap to release

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#562]
I tried to outline what is missing before we could cut a release with the new graph stuff. Open to a discussion.

## testing

We have a decent coverage of base but especially constructors are not always tested for correctness. So we test the API but not that the adjacency captures what it should. So missing tests:

- [ ] test correctness of contiguity builders
- [ ] test correctness of triangulation builders
- [ ] test correctness of kernel builders
- [ ] test all kernel parameters
- [ ] test all query options (both sklearn and scipy)
- [ ] test precomputed distance matrix support

## implementation/checks

Some bits are still waiting for implementation (I have likely missed stuff here) or a double check that the current implementation works as intended. 

- [ ] isolates in kernel and knn
- [ ] co-located in knn
- [ ] knn haversine checks
- [ ] set ops implementation and tests
- [ ] fix cliques
- [ ] set operations
- [ ] draft API and raise NotImplementedError?

## discussion

A few things I'd like to discuss (during the dev call in 3 minutes?)

- [ ] default kernel - W has triangular, we now have gaussian following scipy model
- [ ] expose kernels in `transform`? kernels are essentially transformations. Shall we allow to use them post-creation?
- [ ] how should set operations work? See #561 

## follow-up

Stuff that is not implemented or started but that can likely wait for subsequent release, not the initial one. Below is the list of stuff I'd like to see soon but there's more to be done.

- [ ] lag_categorical (inside `lag()`?)
- [ ] classic I/O (we have custom Parquet now)
- [ ] plotting
- [ ] fuzzy contiguity (should be straightforward)
- [ ] other utils - any priorities?

Some of the follow-up could be piped via W for the time being if we want them available.

**Comment by martinfleis** [comment]
Can you drop a note if you are planning to work on any of the topics mentioned above so we don't overlap?

**Comment by ljwolf** [comment]
I am unlikely to have time until sept 27

**Comment by knaaptime** [comment]
I think I’ll go back to ensuring the constructors can consume sparse next

**Comment by martinfleis** [comment]
With #577, we're ready for the initial _experimental_ release of Graph. 

- cliques are not fixed, but they raise `NotImplementedError` at the moment.
- precomputed matrix is not tested explicitly but a few of our internal functions use it, so it is tested via those.
- API is not yet drafted, but that does not need to be for a release
- The default kernel is still Gaussian
- set operations are implemented with some restrictions ensuring the validity of the Graph and its alignment with original data. See #575 for details.

Anything else you'd like to get in?

I would target the end of the week at the latest to cut 4.8.0 (need it alive on conda on Tuesday)

**Comment by martinfleis** [comment]
Anything blocking the release now that #577 is merged?

@jGaboardi any idea if the current infrastructure works as intended? It has not been updated here.

**Comment by jGaboardi** [comment]
I am not sure. Let's give it try; perhaps as a `4.7.0.post1` release?

**Comment by martinfleis** [comment]
More like `4.8.0.rc1` given the status of current `main`

**Comment by martinfleis** [comment]
@jGaboardi Action looking good - https://github.com/pysal/libpysal/actions/runs/6353690175/job/17258825775

PyPI is up - https://pypi.org/project/libpysal/4.8.0rc1/

Changelog is completely broken - https://github.com/pysal/libpysal/releases/tag/v4.8.0rc1

**Comment by martinfleis** [comment]
Documentation is okay - https://pysal.org/libpysal/

**Comment by jGaboardi** [comment]
> Changelog is completely broken

Yeah, looks like [the action](https://github.com/pysal/libpysal/blob/a495cb908601d6fac0cf4dca72153a8b1dfaa71e/.github/workflows/release_and_publish.yml#L37-L39) still uses [`tools/gitcount.ipynb`](https://github.com/pysal/libpysal/blob/main/tools/gitcount.ipynb). This will need to be looked it if we still want to use it.

`spaghetti` has been using [`actions/github-script@v6`](https://github.com/pysal/spaghetti/blob/fd8f98e0dd39f11360aab7c7bcb8e3b39da2f9c7/.github/workflows/release_and_publish.yml#L41-L49) with [success](https://github.com/pysal/spaghetti/releases/tag/v1.7.4), if we want to try here.

**Comment by knaaptime** [comment]
lets update the root and get rid of versioneer etc before doing a real release

**Comment by martinfleis** [comment]
@knaaptime Are you on it or shall I?

**Comment by knaaptime** [comment]
i'll take the first pass

**Comment by martinfleis** [comment]
Unless anyone does that first, I'm happy to cut 4.8.0 later tonight (Prague time) or tomorrow morning.

**Comment by jGaboardi** [comment]
> Unless anyone does that first, I'm happy to cut 4.8.0 later tonight (Prague time) or tomorrow morning.

Seem to have a strange merge problem with `upstream/main` vs. my `main`. Both [docs build](https://github.com/pysal/libpysal/actions/runs/6372478347) and [publish](https://github.com/pysal/libpysal/actions/runs/6372478335) failed. Going to delete the `v4.8.0` tag and try to figure it out.

**Comment by jGaboardi** [comment]
Seems like two key pieces slipped through the cracks:
1. [Updated method](https://github.com/pysal/mapclassify/blob/4417d314658ffe0d00fef09791a567b8823b9b37/.github/workflows/release.yml#L27-L31) for install deps for creating release.
2. [This line](https://github.com/pysal/mapclassify/blob/main/docs/conf.py#L24) seems to be [missing](https://github.com/pysal/libpysal/actions/runs/6372478347/job/17295293819#step:4:19) in [`libpysal/docs/conf.py`](https://github.com/pysal/libpysal/blob/479ce33e29320376da6f7de0834a1610944238d7/docs/conf.py#L20)

I'll put in the necessary PR shortly.

**Comment by knaaptime** [comment]
we dont need the sys path hack

**Comment by knaaptime** [comment]
i think we're using an old recipe for the docs. It should have an install line before making the docs (so you get the real version without doing the sys/path hack). I think there's a current version in tobler

**Comment by jGaboardi** [comment]
> we dont need the sys path hack

[Seems to fail](https://github.com/pysal/libpysal/actions/runs/6372478347/job/17295293819#step:4:19) without it. Is there something I am missing?

**Comment by jGaboardi** [comment]
@knaaptime @martinfleis 

Can confirm docs build locally, but with the following warnings:

```
libpysal/libpysal/cg/shapes.py:docstring of libpysal.cg.LineSegment.bounding_box:1:<autosummary>:1: WARNING: Inline strong start-string without end-string.
libpysal/libpysal/cg/shapes.py:docstring of libpysal.cg.LineSegment.bounding_box:1:<autosummary>:1: WARNING: Inline strong start-string without end-string.
libpysal/docs/notebooks/fetch.ipynb:4: WARNING: Each notebook should have at least one section title
libpysal/docs/notebooks/io.ipynb:4: WARNING: Each notebook should have at least one section title
libpysal/docs/notebooks/Raster_awareness_API.ipynb: WARNING: document isn't included in any toctree
libpysal/docs/notebooks/fetch.ipynb: WARNING: document isn't included in any toctree
libpysal/docs/notebooks/io.ipynb: WARNING: document isn't included in any toctree
```

* The first two, I can't find anything to actually fix after finding [some possible solution](https://documatt.com/blog/sphinx-errors/5-inline-literal-start-string-without-end-string.html).
* The second two are "whatevers".
* For the final three, are we not including those in [`tutorial.rst`](https://github.com/pysal/libpysal/blob/main/docs/tutorial.rst) on purpose? If so, then nothing to fix.

**Comment by jGaboardi** [comment]
I we are OK with that, I will push up the fixes immediately.

**Comment by jGaboardi** [comment]
[Release failed](https://github.com/pysal/libpysal/actions/runs/6372923548/job/17296195063#step:5:2094), I think because there is no `README.md` in `libpysal`... it's [`README.rst`](https://github.com/pysal/libpysal/blob/main/README.rst).

**Comment by jGaboardi** [comment]
@knaaptime @martinfleis 

`v4.8.0rc2` is [tagged](https://github.com/pysal/libpysal/releases) and up on [PyPI](https://pypi.org/project/libpysal/4.8.0rc2/) with [docs built successfully](https://pysal.org/libpysal/). Please give a once over. If everything looks kosher, I will cut `v4.8.0`.

**Comment by martinfleis** [comment]
All looking good to me!

**Comment by jGaboardi** [comment]
Do you or Eli want to do the honors since yall put in that hard work? Or shall I go ahead and cut it?

**Comment by martinfleis** [comment]
Go ahead 😉

**Comment by martinfleis** [comment]
The decision on ID API has been to allow passing an array of IDs when the input is a sparse or dense precomputed array and raise a `ValueError` when it is passed alongside a data frame.

**Comment by jGaboardi** [comment]
xref #712

**Comment by knaaptime** [comment]
I just got an email asking whether the `lat2w` functions were available on the `Graph`, and I cant remember if we had any discussion about that. AFAICT we ignored all the lattice stuff (though we do have the h3 builder)?

**Comment by sjsrey** [comment]
> I just got an email asking whether the `lat2w` functions were available on the `Graph`, and I cant remember if we had any discussion about that. AFAICT we ignored all the lattice stuff (though we do have the h3 builder)?

Since `lat2w` wasn't a member of `W` it wasn't ported: https://pysal.org/libpysal/migration.html

We could add a helper function `lat2g` which under the hood calls `lat2w`  and returns `Graph.from_W` ?  Or just builds the `Graph` directly so we don't call `lat2w`?

**Comment by martinfleis** [comment]
I actually made an attempt of implementing that but it was dead slow and low priority so I gave up at the time.

**Comment by ljwolf** [comment]
If we're changing it, could we call it something like lattice()?

**Comment by martinfleis** [comment]
Given it is a builder, so `Graph.build_lattice`?

**Comment by martinfleis** [comment]
It now exists as `Graph.from_lattice` - https://github.com/pysal/libpysal/pull/912
