### ISSUE TITLE
lint repo with `ruff`, update `pyproject.toml` and pre-commit for linting

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#589]
lint repo with `ruff`, update `pyproject.toml` and pre-commit for linting.

* [x] `__init__` in all levels – #597 
* [x] top level `.py` files – #597 
* [x] `cg`
  * [x] `./cg/*.py` – #608 
  * [x] `./cg/ops/*.py` – #610
  * [x] `./cg/ops/tests/*.py` – #611 
  * [x] `./cg/tests/*.py` – #614
* [x] `examples` – #607 
* [x] `graph`
  * [x] `./graph/base.py` – #615
  * [x] `./graph/_*.py` – #618
  * [x] `./graph/tests/*.py` – #619
* [x] `io`
  * [x] `./io/*.py` – #620
  * [x] `./io/geotable/*` – #622 
  * [x] `./io/iohandlers/*` – (#630)
      * #637 
      * #638
      * #641 
      * #642 
      * #643 
  * [x] `./io/{tests,util}/*`
      * #644 
      * #645 
      * #646 
* [x] `weights`
  * https://github.com/pysal/libpysal/pull/648
  * #650 
  * #651 
  * #652 
  * #653 
  * #654 
  * #655 
  * #658 
* [x] review and final pass
  * [x] convert `# noqa <CODE>` -->   `# noqa: <CODE>` – #660 
     * Without that colon, any violation is skipped, not only the one from `<CODE>` 
  * [x] other rough edges? – #661 
* [x] update infra
  * [x] `pyproject.toml`– #661 
  * [x] `.pre-commit-config.yaml`– #661 
  * [x] enable `pre-commit` on triggered GHA – https://results.pre-commit.ci

**Comment by jGaboardi** [comment]
xref #594

**Comment by jGaboardi** [comment]
All files formatted and listed; pre-commit hook for CI/PRs is enabled.
